[solution]
name = "gdn-decode-v1"      # Solution name
definition = "gdn_decode_qk4_v8_d128_k_last"          # Track: fused_moe | sparse_attention | gated_delta_net
author = "KimJangMaengShin/jsg1504"              # Team/author name

[build]
language = "cuda"                 # python | triton | cuda
entry_point = "kernel.cu::kernel"   # Entry point: <file_path>::<function_name>
destination_passing_style = true
